### ISSUE TITLE
[question] How are training images and testing images split?

### ISSUE THREAD

**Issue by lancercat** [harshlunia7/IndicSTR12_ICDAR#1]
Hi, thanks for sharing the code,
Can you help specifying the exact training data and testing data split for Table 5 in the corresponding paper[1],
i.e. which sample goes to train_lmdb, which goes into val_lmdb, and which goes into test_lmdb. 

I want to benchmark my method on your dataset too, and want to be as fair as possible.

Huge thanks in advance.
---

[1] https://link.springer.com/chapter/10.1007/978-3-031-41498-5_17

**Comment by harshlunia7** [comment]
Hi, you can download the splits from [here](https://cvit.iiit.ac.in/research/projects/cvit-projects/indicstr#).

However, exact replication may not be possible, as the real data underwent two rounds of verification, while the paper reports results based on the first round of annotations.
